export * from "./Image/Image";
export * from "./Paragraph/Paragraph";
export * from "./SubTitle/SubTitle";
export * from "./Title/Title";
export * from "./Image/Image";
export * from "./Footer/Footer";
export * from "./Header/Header";
export * from "./Main/Main";
export * from "./Paragraph/Paragraph";